In [3]:
import pandas as pd

In [31]:
path = '../data/raw/2007-2020-PIT-Estimates-by-state.xlsx'

In [34]:
pit_coc = pd.read_excel(path, sheet_name=list(range(0, 16)), engine='openpyxl')

In [36]:
pit_coc[1].head()

,State,Number of CoCs,"Overall Homeless, 2020","Overall Homeless - Under 18, 2020","Overall Homeless - Age 18 to 24, 2020","Overall Homeless - Over 24, 2020","Overall Homeless - Female, 2020","Overall Homeless - Male, 2020","Overall Homeless - Transgender, 2020","Overall Homeless - Gender Non-Conforming, 2020",...,"Overall Homeless Parenting Youth Age 18-24, 2020","Sheltered ES Homeless Parenting Youth Age 18-24, 2020","Sheltered TH Homeless Parenting Youth Age 18-24, 2020","Sheltered Total Homeless Parenting Youth Age 18-24, 2020","Unsheltered Homeless Parenting Youth Age 18-24, 2020","Overall Homeless Children of Parenting Youth, 2020","Sheltered ES Homeless Children of Parenting Youth, 2020","Sheltered TH Homeless Children of Parenting Youth, 2020","Sheltered Total Homeless Children of Parenting Youth, 2020","Unsheltered Homeless Children of Parenting Youth, 2020"
0,AK,2.0,1949,326,197,1426,828,1114,3,4,...,13,10,3,13,0,16,12,4,16,0
1,AL,8.0,3351,528,198,2625,1294,1988,9,4,...,27,10,15,25,2,36,13,21,34,2
2,AR,4.0,2366,195,258,1913,798,1561,5,2,...,8,6,1,7,1,12,8,2,10,2
3,AS,0.0,,,,,,,,,...,,,,,,,,,,
4,AZ,3.0,10979,1722,824,8433,4228,6694,43,14,...,98,33,54,87,11,128,48,72,120,8

In [23]:
list(pit_coc[0].iloc[0, ])

['State',
 'Total Year-Round Beds (ES, TH, SH)',
 'Total Non-DV Year-Round Beds (ES, TH, SH)',
 'Total HMIS Year-Round Beds (ES, TH, SH)',
 'HMIS Participation Rate for Year-Round Beds (ES, TH, SH)',
 'Total Year-Round Beds (ES)',
 'Total Year-Round Beds (TH)',
 'Total Year-Round Beds (SH)',
 'Total Units for Households with Children (ES, TH, SH)',
 'Total Beds for Households with Children (ES, TH, SH)',
 'Total Beds for Households without Children (ES, TH, SH)',
 'Total Beds for Households with only Children (ES, TH, SH)',
 'Dedicated Veteran Beds (ES, TH, SH)',
 'Dedicated Youth Beds (ES, TH, SH)',
 'Total Year-Round Beds (ES)',
 'Total Non-DV Year-Round Beds (ES)',
 'Total HMIS Year-Round Beds (ES)',
 'HMIS Participation Rate for Year-Round Beds (ES)',
 'Total Seasonal Beds (ES)',
 'Total Overflow Beds (ES)',
 'Total Units for Households with Children (ES)',
 'Total Beds for Households with Children (ES)',
 'Total Beds for Households without Children (ES)',
 'Total Beds for Households with only Children (ES)',
 'Dedicated Veteran Beds (ES)',
 'Dedicated Youth Beds (ES)',
 'Total Year-Round Beds (TH)',
 'Total Non-DV Year-Round Beds (TH)',
 'Total HMIS Year-Round Beds (TH)',
 'HMIS Participation Rate for Year-Round Beds (TH)',
 'Total Units for Households with Children (TH)',
 'Total Beds for Households with Children (TH)',
 'Total Beds for Households without Children (TH)',
 'Total Beds for Households with only Children (TH)',
 'Dedicated Veteran Beds (TH)',
 'Dedicated Youth Beds (TH)',
 'Total Year-Round Beds (SH)',
 'Total Non-DV Year-Round Beds (SH)',
 'Total HMIS Year-Round Beds (SH)',
 'HMIS Participation Rate for Year-Round Beds (SH)',
 'Total Units for Households with Children (SH)',
 'Total Beds for Households with Children (SH)',
 'Total Beds for Households without Children (SH)',
 'Total Beds for Households with only Children (SH)',
 'Dedicated Veteran Beds (SH)',
 'Dedicated Youth Beds (SH)',
 'Total Year-Round Beds (RRH)',
 'Total Non-DV Year-Round Beds (RRH)',
 'Total HMIS Year-Round Beds (RRH)',
 'HMIS Participation Rate for Year-Round Beds (RRH)',
 'Total Units for Households with Children (RRH)',
 'Total Beds for Households with Children (RRH)',
 'Total Beds for Households without Children (RRH)',
 'Total Beds for Households with only Children (RRH)',
 'Dedicated Veteran Beds (RRH)',
 'Dedicated Youth Beds (RRH)',
 'Total Year-Round Beds (PSH)',
 'Total Non-DV Year-Round Beds (PSH)',
 'Total HMIS Year-Round Beds (PSH)',
 'HMIS Participation Rate for Year-Round Beds (PSH)',
 'Total Units for Households with Children (PSH)',
 'Total Beds for Households with Children (PSH)',
 'Total Beds for Households without Children (PSH)',
 'Total Beds for Households with only Children (PSH)',
 'Dedicated Veteran Beds (PSH)',
 'Dedicated Youth Beds (PSH)',
 'Dedicated Chronically Homeless Beds (PSH)',
 'Total Year-Round Beds (OPH)',
 'Total Non-DV Year-Round Beds (OPH)',
 'Total HMIS Year-Round Beds (OPH)',
 'HMIS Participation Rate for Year-Round Beds (OPH)',
 'Total Units for Households with Children (OPH)',
 'Total Beds for Households with Children (OPH)',
 'Total Beds for Households without Children (OPH)',
 'Total Beds for Households with only Children (OPH)',
 'Dedicated Veteran Beds (OPH)',
 'Dedicated Youth Beds (OPH)']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#expected, preprocessed output 
expected = pd.read_csv('/content/drive/MyDrive/DS4_project data/CA_pit')
expected.head()

  State  Number of CoCs  ...  Unsheltered Homeless Children of Parenting Youth  year
0    CA              44  ...                                             459.0  2020
1    CA              44  ...                                             282.0  2019
2    CA              43  ...                                             120.0  2018
3    CA              43  ...                                             130.0  2017
4    CA              43  ...                                             163.0  2016

[5 rows x 542 columns]

In [ ]:
pit_coc.keys()

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])

In [28]:
all_dfs = []

for index in pit_coc:

  df = pit_coc[index]
  # df.columns = pit_coc[0].iloc[0, ]
  # df = df[1:]
  # print(df.head())
  # break
  year = int(df.columns[3].split(',')[1])
  
  # # print(df.columns[3], year)
  # df['year'] = year

  # new_column_names = []
  # for c in df.columns:
  #   no_year = c.replace(', '+str(year), '')
  #   new_column_names.append(no_year)
  
  # df = df.set_axis(new_column_names, axis=1, inplace=False)
  # all_dfs.append(df)
df.columns

Index(['State', 'Total Year-Round Beds (ES, TH, SH)',
       'Total Non-DV Year-Round Beds (ES, TH, SH)',
       'Total HMIS Year-Round Beds (ES, TH, SH)',
       'HMIS Participation Rate for Year-Round Beds (ES, TH, SH)',
       'Total Year-Round Beds (ES)', 'Total Year-Round Beds (TH)',
       'Total Year-Round Beds (SH)',
       'Total Units for Households with Children (ES, TH, SH)',
       'Total Beds for Households with Children (ES, TH, SH)',
       'Total Beds for Households without Children (ES, TH, SH)',
       'Total Beds for Households with only Children (ES, TH, SH)',
       'Dedicated Veteran Beds (ES, TH, SH)',
       'Dedicated Youth Beds (ES, TH, SH)', 'Total Year-Round Beds (ES)',
       'Total Non-DV Year-Round Beds (ES)', 'Total HMIS Year-Round Beds (ES)',
       'HMIS Participation Rate for Year-Round Beds (ES)',
       'Total Seasonal Beds (ES)', 'Total Overflow Beds (ES)',
       'Total Units for Households with Children (ES)',
       'Total Beds for Households with Children (ES)',
       'Total Beds for Households without Children (ES)',
       'Total Beds for Households with only Children (ES)',
       'Dedicated Veteran Beds (ES)', 'Dedicated Youth Beds (ES)',
       'Total Year-Round Beds (TH)', 'Total Non-DV Year-Round Beds (TH)',
       'Total HMIS Year-Round Beds (TH)',
       'HMIS Participation Rate for Year-Round Beds (TH)',
       'Total Units for Households with Children (TH)',
       'Total Beds for Households with Children (TH)',
       'Total Beds for Households without Children (TH)',
       'Total Beds for Households with only Children (TH)',
       'Dedicated Veteran Beds (TH)', 'Dedicated Youth Beds (TH)',
       'Total Year-Round Beds (SH)', 'Total Non-DV Year-Round Beds (SH)',
       'Total HMIS Year-Round Beds (SH)',
       'HMIS Participation Rate for Year-Round Beds (SH)',
       'Total Units for Households with Children (SH)',
       'Total Beds for Households with Children (SH)',
       'Total Beds for Households without Children (SH)',
       'Total Beds for Households with only Children (SH)',
       'Dedicated Veteran Beds (SH)', 'Dedicated Youth Beds (SH)',
       'Total Year-Round Beds (RRH)', 'Total Non-DV Year-Round Beds (RRH)',
       'Total HMIS Year-Round Beds (RRH)',
       'HMIS Participation Rate for Year-Round Beds (RRH)',
       'Total Units for Households with Children (RRH)',
       'Total Beds for Households with Children (RRH)',
       'Total Beds for Households without Children (RRH)',
       'Total Beds for Households with only Children (RRH)',
       'Dedicated Veteran Beds (RRH)', 'Dedicated Youth Beds (RRH)',
       'Total Year-Round Beds (PSH)', 'Total Non-DV Year-Round Beds (PSH)',
       'Total HMIS Year-Round Beds (PSH)',
       'HMIS Participation Rate for Year-Round Beds (PSH)',
       'Total Units for Households with Children (PSH)',
       'Total Beds for Households with Children (PSH)',
       'Total Beds for Households without Children (PSH)',
       'Total Beds for Households with only Children (PSH)',
       'Dedicated Veteran Beds (PSH)', 'Dedicated Youth Beds (PSH)',
       'Dedicated Chronically Homeless Beds (PSH)',
       'Total Year-Round Beds (OPH)', 'Total Non-DV Year-Round Beds (OPH)',
       'Total HMIS Year-Round Beds (OPH)',
       'HMIS Participation Rate for Year-Round Beds (OPH)',
       'Total Units for Households with Children (OPH)',
       'Total Beds for Households with Children (OPH)',
       'Total Beds for Households without Children (OPH)',
       'Total Beds for Households with only Children (OPH)',
       'Dedicated Veteran Beds (OPH)', 'Dedicated Youth Beds (OPH)'],
      dtype='object', name=0)

In [ ]:
all_dfs.to_csv('/content/drive/MyDrive/DS4_project data/pit_by_coc.csv', index=False)

AttributeError: ignored

In [ ]:
pit_coc = pd.concat(all_dfs)
pit_coc.to_csv('/content/drive/MyDrive/DS4_project data/pit_by_coc.csv', index=False)

In [ ]:
pit_coc['CoC Number'] == 'CA-600'

0      False
1      False
2      False
3      False
4      False
       ...
390    False
391    False
392    False
393    False
394    False
Name: CoC Name, Length: 395, dtype: bool

In [ ]:
pit_coc[pit_coc['CoC Number'] == 'CA-600'].to_csv('/content/drive/MyDrive/DS4_project data/CA-600-2018.csv', index=False)

In [ ]:
bool_ca = pit_coc['CoC Number'] == 'CA-600'

In [ ]:
pit_coc[bool_ca]

   CoC Number  ... Unsheltered Homeless Children of Parenting Youth, 2018
48     CA-600  ...                                               22.0

[1 rows x 541 columns]